CREATE TABLE Employee,
(EmpNo VARCHAR(8) NOT NULL,
 EmpName VARCHAR(30) NOT NULL,
 Department VARCHAR(30) NOT NULL,
 Email VARCHAR(50) NOT NULL,
 Phone VARCHAR(8) NOT NULL,
 CONSTRAINT PK_Employee PRIMARY KEY (EmpNo));