CREATE TABLE EventPlan,
(PlanNo VARCHAR(8) NOT NULL
EventNo VARCHAR(8) NOT NULL,
WorkDate DATE NOT NULL,
Notes VARCHAR(30),
Activity VARCHAR(30) NOT NULL,
 EmpNo VARCHAR(8), 
 CONSTRAINT PK_EventPlan PRIMARY KEY (PlanNo),
 CONSTRAINT FK_EventNo FOREIGN KEY (EventNo)
 REFERENCES EventRequest(EventNo)
 CONSTRAINT FK_EmpNo FOREIGN KEY (EmpNo)
 REFERENCES Employee(EmpNo));